"""added last_updated to patients

Revision ID: 1d34f4c2f660
Revises: 750a157a1fcf
Create Date: 2026-05-07 14:25:30.644647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d34f4c2f660'
down_revision: Union[str, Sequence[str], None] = '750a157a1fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('last_updated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'last_updated')
    # ### end Alembic commands ###
