"""changed last_update for medication to nullable

Revision ID: 750a157a1fcf
Revises: 318e95540de7
Create Date: 2026-05-06 20:33:14.458616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750a157a1fcf'
down_revision: Union[str, Sequence[str], None] = '318e95540de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medications', 'last_updated',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medications', 'last_updated',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
