"""added extra tables based on sample data

Revision ID: 7d3030fa6c00
Revises: 5df0742688a9
Create Date: 2026-05-06 00:32:10.724865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3030fa6c00'
down_revision: Union[str, Sequence[str], None] = '5df0742688a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age_years', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'age_years')
    # ### end Alembic commands ###
