"""add mrn to patient

Revision ID: 8f648fd2a781
Revises: 00493b5ad351
Create Date: 2026-05-06 00:04:37.994742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f648fd2a781'
down_revision: Union[str, Sequence[str], None] = '00493b5ad351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('mrn', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_column('patients', 'mrn')
    # ### end Alembic commands ###
