"""make vital signs last updated nullable

Revision ID: 990cb00b3168
Revises: 1d34f4c2f660
Create Date: 2026-05-22 17:15:00.403072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990cb00b3168'
down_revision: Union[str, Sequence[str], None] = '1d34f4c2f660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vital_signs', 'last_updated',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vital_signs', 'last_updated',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
