"""create medications table

Revision ID: c96285d4c21b
Revises: 11ebe4a45b49
Create Date: 2026-05-05 22:40:18.730177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96285d4c21b'
down_revision: Union[str, Sequence[str], None] = '11ebe4a45b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('medication', sa.String(length=100), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('source_reliability', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
